language: go

go:
  - 1.15.x

git:
  depth: 1

env:
  - APPNAME=drone-tardigrade
services:
  - docker

script:
  - go test -v ./...
  - docker build -t kristaxox/drone-tardigrade:${TRAVIS_COMMIT} .

after_success:
  - if [[ "$TRAVIS_BRANCH" == "main" ]]; then
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
      docker push kristaxox/drone-tardigrade:${TRAVIS_COMMIT} ;
      docker tag kristaxox/drone-tardigrade:${TRAVIS_COMMIT} kristaxox/drone-tardigrade:latest ;
      docker push kristaxox/drone-tardigrade:latest ;
    fi