language: go

go:
  - 1.15.x

git:
  depth: 1

env:
  - APPNAME=drone-tardigrade
services:
  - docker

script:
  - go test -v ./...
  - docker build -t kristaxox/${APPNAME}:${TRAVIS_COMMIT} .

after_success:
  - if [[ "$TRAVIS_BRANCH" == "main" ]]; then
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
      docker push kristaxox/${APPNAME}:${TRAVIS_COMMIT} ;
      docker tag kristaxox/${APPNAME}:${TRAVIS_COMMIT} kristaxox/${APPNAME}:latest ;
      docker push kristaxox/${APPNAME}:latest ;
    fi